import type { Workspace } from "./types";
export const DEMO_DATE = "2026-10-09";
export function demoWorkspace(): Workspace {
  return {
    cases: [
      {
        id: 1,
        title: "Meera’s maintenance case",
        status: "ACTIVE",
        createdAt: "2026-04-12",
        legalRoute: "Maintenance proceeding",
        description: "Synthetic case for exploring Alimony Plus.",
      },
      {
        id: 2,
        title: "Child education support",
        status: "ACTIVE",
        createdAt: "2026-08-18",
        legalRoute: "Support review",
      },
    ],
    proceedings: [
      {
        id: 1,
        caseId: 1,
        courtName: "Family Court, New Delhi",
        caseNumber: "DEMO / 2026 / 0142",
        proceedingType: "Interim maintenance",
        status: "ONGOING",
        filedAt: "2026-04-12",
      },
      {
        id: 2,
        caseId: 2,
        courtName: "Family Court, New Delhi",
        caseNumber: "DEMO / 2026 / 0238",
        proceedingType: "Education support",
        status: "ONGOING",
        filedAt: "2026-08-18",
      },
    ],
    orders: [
      {
        id: 1,
        proceedingId: 1,
        orderType: "Interim maintenance",
        orderDate: "2026-05-22",
        amount: 15000,
        effectiveDate: "2026-06-01",
        dueDay: 5,
        description:
          "Synthetic monthly schedule. Payment due on the 5th of each month.",
      },
    ],
    payments: [
      {
        id: 1,
        orderId: 1,
        amount: 15000,
        paymentDate: "2026-06-04",
        period: "2026-06",
        status: "RECEIVED",
        reference: "DEMO-JUN",
      },
      {
        id: 2,
        orderId: 1,
        amount: 15000,
        paymentDate: "2026-07-05",
        period: "2026-07",
        status: "RECEIVED",
        reference: "DEMO-JUL",
      },
      {
        id: 3,
        orderId: 1,
        amount: 15000,
        paymentDate: "2026-08-05",
        period: "2026-08",
        status: "RECEIVED",
        reference: "DEMO-AUG",
      },
      {
        id: 4,
        orderId: 1,
        amount: 10000,
        paymentDate: "2026-09-06",
        period: "2026-09",
        status: "RECEIVED",
        reference: "DEMO-SEP",
      },
    ],
    hearings: [
      {
        id: 1,
        caseId: 1,
        date: "2026-10-16",
        title: "Maintenance review hearing",
        location: "Family Court, New Delhi · Courtroom 3",
      },
      {
        id: 2,
        caseId: 2,
        date: "2026-10-23",
        title: "Document review",
        location: "Meeting with legal-aid counsel",
      },
    ],
    documents: [
      {
        id: 1,
        caseId: 1,
        originalName: "Interim-maintenance-order.pdf",
        documentType: "Court order",
        fileSize: 245000,
        createdAt: "2026-05-22",
      },
      {
        id: 2,
        caseId: 1,
        originalName: "September-payment-receipt.pdf",
        documentType: "Payment proof",
        fileSize: 86000,
        createdAt: "2026-09-06",
      },
      {
        id: 3,
        caseId: 1,
        originalName: "Monthly-expense-summary.pdf",
        documentType: "Financial record",
        fileSize: 124000,
        createdAt: "2026-09-28",
      },
    ],
    sources: [
      {
        id: 1,
        title: "Essential household expenses",
        kind: "Financial fact",
        url: "",
        section: "Synthetic monthly budget",
        reviewedOn: "",
        effectiveFrom: "2026-09-01",
        status: "Needs review",
        value: "18000",
        frequency: "Monthly",
        certainty: "Estimated",
      },
      {
        id: 2,
        title: "Respondent income",
        kind: "Financial fact",
        url: "",
        section: "Not provided",
        reviewedOn: "",
        effectiveFrom: "",
        status: "Needs review",
        value: "",
        frequency: "Monthly",
        certainty: "Unknown",
      },
    ],
  };
}
